<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'translator' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/translation-contracts/LocaleAwareInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/translation/TranslatorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/translation-contracts/TranslatorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/translation/TranslatorBagInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/translation/Translator.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Translation/Translator.php';
include_once $this->targetDirs[3].'/vendor/symfony/translation/Formatter/MessageFormatterInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/translation/Formatter/IntlFormatterInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/translation/Formatter/ChoiceMessageFormatterInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/translation/Formatter/MessageFormatter.php';
include_once $this->targetDirs[3].'/vendor/symfony/translation-contracts/TranslatorTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/translation/IdentityTranslator.php';

$this->services['translator'] = $instance = new \Symfony\Bundle\FrameworkBundle\Translation\Translator(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'translation.loader.csv' => ['privates', 'translation.loader.csv', 'getTranslation_Loader_CsvService.php', true],
    'translation.loader.dat' => ['privates', 'translation.loader.dat', 'getTranslation_Loader_DatService.php', true],
    'translation.loader.ini' => ['privates', 'translation.loader.ini', 'getTranslation_Loader_IniService.php', true],
    'translation.loader.json' => ['privates', 'translation.loader.json', 'getTranslation_Loader_JsonService.php', true],
    'translation.loader.mo' => ['privates', 'translation.loader.mo', 'getTranslation_Loader_MoService.php', true],
    'translation.loader.php' => ['privates', 'translation.loader.php', 'getTranslation_Loader_PhpService.php', true],
    'translation.loader.po' => ['privates', 'translation.loader.po', 'getTranslation_Loader_PoService.php', true],
    'translation.loader.qt' => ['privates', 'translation.loader.qt', 'getTranslation_Loader_QtService.php', true],
    'translation.loader.res' => ['privates', 'translation.loader.res', 'getTranslation_Loader_ResService.php', true],
    'translation.loader.xliff' => ['privates', 'translation.loader.xliff', 'getTranslation_Loader_XliffService.php', true],
    'translation.loader.yml' => ['privates', 'translation.loader.yml', 'getTranslation_Loader_YmlService.php', true],
], [
    'translation.loader.csv' => '?',
    'translation.loader.dat' => '?',
    'translation.loader.ini' => '?',
    'translation.loader.json' => '?',
    'translation.loader.mo' => '?',
    'translation.loader.php' => '?',
    'translation.loader.po' => '?',
    'translation.loader.qt' => '?',
    'translation.loader.res' => '?',
    'translation.loader.xliff' => '?',
    'translation.loader.yml' => '?',
]), new \Symfony\Component\Translation\Formatter\MessageFormatter(new \Symfony\Component\Translation\IdentityTranslator()), 'en', ['translation.loader.php' => [0 => 'php'], 'translation.loader.yml' => [0 => 'yaml', 1 => 'yml'], 'translation.loader.xliff' => [0 => 'xlf', 1 => 'xliff'], 'translation.loader.po' => [0 => 'po'], 'translation.loader.mo' => [0 => 'mo'], 'translation.loader.qt' => [0 => 'ts'], 'translation.loader.csv' => [0 => 'csv'], 'translation.loader.res' => [0 => 'res'], 'translation.loader.dat' => [0 => 'dat'], 'translation.loader.ini' => [0 => 'ini'], 'translation.loader.json' => [0 => 'json']], ['cache_dir' => ($this->targetDirs[0].'/translations'), 'debug' => true, 'resource_files' => [], 'scanned_directories' => [0 => ($this->targetDirs[3].'/translations'), 1 => ($this->targetDirs[3].'/vendor/symfony/framework-bundle/Resources/translations'), 2 => ($this->targetDirs[3].'/src/Resources/FrameworkBundle/translations'), 3 => ($this->targetDirs[3].'/src/Resources/translations')]]);

$instance->setConfigCacheFactory(($this->privates['config_cache_factory'] ?? $this->getConfigCacheFactoryService()));
$instance->setFallbackLocales([0 => 'en']);

return $instance;
