<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKxSxx7t\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKxSxx7t/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKxSxx7t.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKxSxx7t\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKxSxx7t\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KxSxx7t',
    'container.build_id' => '789fb437',
    'container.build_time' => 1574685856,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKxSxx7t');
