<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBgyBsxx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBgyBsxx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBgyBsxx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBgyBsxx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBgyBsxx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BgyBsxx',
    'container.build_id' => '36a5363e',
    'container.build_time' => 1573575304,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBgyBsxx');
