<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNg3R3Oz\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNg3R3Oz/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNg3R3Oz.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNg3R3Oz\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNg3R3Oz\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ng3R3Oz',
    'container.build_id' => '9dc832b4',
    'container.build_time' => 1573562370,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNg3R3Oz');
